#
# gen_includes.py - regenerate the SD BASIC include files that are derived
#                   from C headers in gplsrc.
#
# command line: python3 gplbld/gen_includes.py [--check] [--gplsrc DIR] [--sdsys DIR]
# eg  cd sdb_ai/sd64 && python3 gplbld/gen_includes.py --check
#
# Three BASIC include records are generated from C headers rather than edited:
#
#   gplsrc/revstamp.h  ->  sdsys/gpl.bp/REVSTAMP.H      (was GPL.BP/REVSTAMP)
#   gplsrc/err.h       ->  sdsys/syscom/ERR.H           (was GPL.BP/ERRGEN)
#   gplsrc/err.h       ->  sdsys/gpl.bp/ERRTEXT.H       (was GPL.BP/ERRGEN)
#
# This script replaces the first two of those generators at build time.  It is
# not a rewrite of them for its own sake - it exists because running them from
# inside SD required the C source tree to be present in the database, which the
# Windows install layout does not allow (PROJECT_STATUS.md 5.8).  The $execute
# directives that ran them automatically during compilation are commented out
# in GPL.BP/CPROC, GPL.BP/APISRVR and GPL.BP/ERRTEXT.
#
# ERRGEN was the dangerous one.  It truncates both of its outputs before it
# opens its input, so with gplsrc absent it destroyed SYSCOM/ERR.H and left
# every ER$ constant in the system undefined - which does not fail the compile,
# it only produces "is not assigned a value" warnings, and then aborts at run
# time in whatever program next touches one.  This script writes nothing until
# it has read everything.
#
# GPL.BP/OPGEN, which generates GPL.BP/OPCODES.H from gplsrc/opcodes.h, is NOT
# ported here.  Nothing ever $executed it, so it is a manual tool and this
# change does not break it, but it does still read ./gplsrc relative to the
# account directory and so must be ported before opcodes can be regenerated on
# an installed system.
#
# The translations below reproduce what the BASIC programs did, character for
# character, including the oddities: TRIM() collapses runs of embedded spaces,
# which is what makes FIELD(rec, ' ', 3) find the error number in a #define
# padded out with spaces; and the first underscore of a #define name becomes
# '$' while the rest become '.', which is why ER_ACC_EXISTS is ER$ACC.EXISTS.
#

import argparse
import os
import sys
import time

# ---------------------------------------------------------------------------
# SD BASIC string primitives, as the original programs relied on them
# ---------------------------------------------------------------------------


def sd_trim(s):
    """TRIM(s) - remove leading and trailing spaces and reduce each run of
    embedded spaces to a single space."""
    return ' '.join([w for w in s.split(' ') if w != ''])


def sd_trimf(s):
    """TRIMF(s) - remove leading spaces only."""
    return s.lstrip(' ')


def sd_trimb(s):
    """TRIMB(s) - remove trailing spaces only."""
    return s.rstrip(' ')


def sd_field(s, delim, n):
    """FIELD(s, delim, n) - 1 based, empty string if there are fewer than n."""
    parts = s.split(delim)
    if n < 1 or n > len(parts):
        return ''
    return parts[n - 1]


def replace_first(s, old, new):
    """CHANGE(s, old, new, 1) - replace the first occurrence only."""
    return s.replace(old, new, 1)


def read_header(path):
    """Read a C header as lines with the line terminator removed.  The headers
    are plain ASCII; read them as latin-1 so no byte can fail to decode."""
    with open(path, 'r', encoding='latin-1', newline='') as f:
        text = f.read()
    lines = text.replace('\r\n', '\n').replace('\r', '\n').split('\n')
    if lines and lines[-1] == '':
        lines.pop()             # trailing terminator, not a final empty record
    return lines


# ---------------------------------------------------------------------------
# GPL.BP/REVSTAMP - gplsrc/revstamp.h -> GPL.BP/REVSTAMP.H
# ---------------------------------------------------------------------------


def gen_revstamp(src_lines):
    out = []
    for rec in src_lines:
        rec = sd_trimf(rec)
        if rec[:2] == '/*':
            rec = rec[1:]
        rec = rec.replace('*/', '')
        if rec[:1] == '#':
            rec = '$' + rec[1:]
            rec = rec.replace('_', '.')
        out.append(rec)
    return out


# ---------------------------------------------------------------------------
# GPL.BP/ERRGEN - gplsrc/err.h -> SYSCOM/ERR.H and GPL.BP/ERRTEXT.H
# ---------------------------------------------------------------------------


def gen_errgen(src_lines, stamp):
    errtext = ['* ERRTEXT.H',
               '* Generated by ERRGEN at ' + stamp,
               '']
    syscom = []

    for rec in src_lines:
        trec = sd_trim(rec)

        if trec[:7] == '#define':
            number = sd_field(trec, ' ', 3)
            text = sd_field(trec, '*', 2).replace('(dos)', '')
            text = sd_trim(text)
            errtext.append('err<-1> = "' + number + '"; text<-1> = "' +
                           text + '"')

        if trec == '':
            syscom.append('')
        elif rec[:2] == '//':
            pass                                    # ERRGEN drops these
        elif rec[:7] == '#define':
            rec = '$' + rec[1:]
            rec = replace_first(rec, '_', '$')      # ER_ACC_EXISTS ->
            rec = rec.replace('_', '.')             #   ER$ACC.EXISTS
            rec = rec.replace('/*', ';*')
            rec = rec.replace('*/', '')
            syscom.append(sd_trimb(rec))
        else:
            rec = '* ' + rec[3:]                    # drops the " * " margin
            rec = rec.replace('*/', '')
            syscom.append(sd_trimb(rec))

    return syscom, errtext


# ---------------------------------------------------------------------------


GENERATED_AT = '* Generated by ERRGEN at '


def compare(path, wanted):
    """Report whether the file on disk matches, ignoring the generation
    timestamp, which is not information about the content."""
    if not os.path.exists(path):
        return 'missing'
    have = read_header(path)
    a = [ln for ln in have if not ln.startswith(GENERATED_AT)]
    b = [ln for ln in wanted if not ln.startswith(GENERATED_AT)]
    if a == b:
        return None
    for i in range(max(len(a), len(b))):
        old = a[i] if i < len(a) else '<end of file>'
        new = b[i] if i < len(b) else '<end of file>'
        if old != new:
            return ('differs from line %d\n       on disk: %s\n     generated: %s'
                    % (i + 1, old, new))
    return 'differs'


def write_lines(path, lines):
    with open(path, 'w', encoding='latin-1', newline='\n') as f:
        for ln in lines:
            f.write(ln + '\n')


def main():
    ap = argparse.ArgumentParser(
        description='Regenerate the BASIC include records derived from gplsrc '
                    'C headers.')
    ap.add_argument('--gplsrc', default='gplsrc',
                    help='C source directory (default: gplsrc)')
    ap.add_argument('--sdsys', default='sdsys',
                    help='SDSYS account directory (default: sdsys)')
    ap.add_argument('--check', action='store_true',
                    help='report what would change and exit non-zero if '
                         'anything would, writing nothing')
    args = ap.parse_args()

    revstamp_h = os.path.join(args.gplsrc, 'revstamp.h')
    err_h = os.path.join(args.gplsrc, 'err.h')
    out_revstamp = os.path.join(args.sdsys, 'gpl.bp', 'REVSTAMP.H')
    out_syscom = os.path.join(args.sdsys, 'syscom', 'ERR.H')
    out_errtext = os.path.join(args.sdsys, 'gpl.bp', 'ERRTEXT.H')

    for path in (revstamp_h, err_h):
        if not os.path.isfile(path):
            sys.exit('gen_includes: cannot read %s' % path)
    for path in (out_revstamp, out_syscom, out_errtext):
        parent = os.path.dirname(path)
        if not os.path.isdir(parent):
            sys.exit('gen_includes: no such directory %s' % parent)

    # Read everything before writing anything.  ERRGEN did the opposite.
    now = time.localtime()
    stamp = time.strftime('%H:%M:%S ', now) + \
        ('%2d ' % now.tm_mday) + time.strftime('%b %Y', now).upper()
    revstamp = gen_revstamp(read_header(revstamp_h))
    err_lines = read_header(err_h)
    syscom, errtext = gen_errgen(err_lines, stamp)

    outputs = ((out_revstamp, revstamp),
               (out_syscom, syscom),
               (out_errtext, errtext))

    if args.check:
        stale = 0
        for path, lines in outputs:
            why = compare(path, lines)
            if why is None:
                print('  in sync  %s' % path)
            else:
                stale += 1
                print('  STALE    %s %s' % (path, why))
        if stale:
            print('%d file(s) out of date - run without --check to '
                  'regenerate' % stale)
        return 1 if stale else 0

    for path, lines in outputs:
        write_lines(path, lines)
        print('  wrote    %s (%d lines)' % (path, len(lines)))
    return 0


if __name__ == '__main__':
    sys.exit(main())
