/* OP_SDEXT.C
 *
 * Copyright (c)2025 The SD Developers, All Rights Reserved
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3, or (at your option)
 * any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software Foundation,
 * Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA. 
 * 
 * 
 * START-HISTORY:
 * 15 Aug 26 Windows port - NullString() no longer returns a STATIC buffer
 *           when malloc fails; the release loop frees what it returns
 * 06 Aug 2024 MAB add SDEXT
 * 08 Aug 2024 mab add embedded python
 * rev 0.9.0 Jan 25 mab add sdext_eguid_set set / restore euid egid of process
 * rev 0.9-2 Mar 25 mab mods for sdext_pyobj
 * END-HISTORY
 *
 * START-DESCRIPTION:
 *
 * Opcodes:
 *    op_sdext    SDEXT   
 *    for basic function SDEXT(Function_id, IsArgMV, Arg)
 *    where:
 *    Function_Id = the integer value used to identify what c code / function is execute.
 *    IsArgMV     = If passing a multiple arguments in Arg, set to true, otherwise false.  
 *    Arg         = string value passed to the c code / function. For functions requiring multiple arguments, set IsArgMV to true 
 *                  and pass arguments in a FIELD_MARK separated string, with a maximum of 10 fields
 *
 * END-DESCRIPTION
 *
 
 * START-CODE
 */


/* 13 Aug 26 Windows port - PATH_MAX comes from <limits.h> here */
#include <limits.h>
#include <sodium.h>

#include <errno.h>

#include "sd.h"
#include "keys.h"
#include "sd_scram.h"
#include "sd_tls.h"
/* 12 Sep 26 Windows port - SD's side of the Python helper pipe, 5.27.  This
   header names no Python type and includes no Python header; the runtimes stay
   apart (5.3) and only bytes cross. */
#include "sdpy_client.h"

/* Modified by Composer AI - 2026/06/10.
   k_error() longjmps and never returns; redeclare noreturn for analyzer. */
void k_error(char msg[], ...) __attribute__((noreturn));
/* -------------------- */

extern char* sd_salt();
extern char* sd_KeyFromPW(char* mypassword, char* mysalt);

/* 13 Aug 26 Windows port - embedded Python removed, see PROJECT_STATUS.md 5.15 */

char* SDMEArgArray[SD_MAX_ARGS];          /* create an array of pointers, for string arguments (for SDEXT call ) not sure if this is correct */
char* NullString(void); 

Private void sdme_err_rsp(int errnbr);
Private void scram_reply(char* value);
Private long scram_arg_long(const char* text);

/* 12 Sep 26 Windows port - the Python adapters, PROJECT_STATUS.md 5.27. */
Private int  py_ext_call(const char* verb, const char* arg,
                         char** payload, size_t* plen);
Private void py_ext_int(const char* verb, const char* arg);
Private void py_ext_str(const char* verb, const char* arg);
Private void py_ext_isinit(void);

extern SDPY* sdpy_session(int* err_code);   /* sdpy_session.c */
extern int   sdpy_session_running(void);

/* ======================================================================
   op_sdext()   op code for BASIC function  SDME.EXT   
   rtnval = SDEXT(Arg,IsArgMV,key)
   rem: code generated by BCOMP will be
   LDSLCL   RTNVAL    Load onto stack short local variable address for RTNVAL
   LDSLCL   ARG       Load onto stack short local variable address for ARG
   LDSLCL   ISARGMV   Load onto stack short local variable address for ISARGMV
   LDSINT   key       Load onto stack short integer
   SDEXT              (op code for op_sdme_ext here)
   STOR               Store onto stack return value in rtnval

      Stack:
        +=============================++=============================+
        +       STACK On Entry        ++       STACK On Exit         +
        +=============================++=============================+
estack> +    next available descr     ++    next available descr     +
        +=============================++=============================+
        +  descriptor w/ integer      ++  Addr to descr for RTNVAL   +
        +      key value              ++                             +
        +=============================++=============================+
        +  descriptor w/ integer      ++   
        +      IsArgMV                ++
        +=============================++
        + Addr to descriptor for Arg  ++   
        +=============================++
		
	   patterned from op_ospath() in op_dio2.c */

void op_sdext() {


  char myErrMsg[SD_ERR_MSG_LEN + 1];    /* hardcoded max string length is set to 512 char need to do something more "durable" */
  int32_t myval_len;
  int32_t mybuf_sz;
  char* myval_buffer;                      /* buffer for past value string  */
  STRING_CHUNK* str;
  int argIdx;
  int argCnt;
  int16_t key;
  int16_t IsArgMV;

  char* myFM = "\xFE";

  DESCRIPTOR* descr;
  
  /* set the process.status flag to  "successful"      */
  /* User can retrieve this status with the BASIC function STATUS()*/
    process.status = 0;

  /* Get action key */
  descr = e_stack - 1;   /* e_stack - 1 points to key descriptor */
  GetInt(descr);
  key = (int16_t)(descr->data.value);
  k_pop(1);   /* after pop() e_stack - 1 points to descr which holds ISArgMV  */

  /* Get IsArgMV Flag */
  descr = e_stack - 1;
  GetInt(descr);
  IsArgMV = (int16_t)(descr->data.value);
  k_pop(1);   /* * after pop() e_stack - 1 points to descr which holds ARG */

  /* Get val string */
  descr = e_stack - 1;
  k_get_string(descr);
  str = descr->data.str.saddr;
  /* is there something there? */
  if (str == NULL){
	  myval_len = 0;  
    mybuf_sz = 1;              /* room for string terminator */
  }else{
	 myval_len =  str->string_len;
     mybuf_sz  =  myval_len+1; /* room for string terminator */
  }
  
  /* allocate space for val string */
  myval_buffer = malloc(mybuf_sz * sizeof(char));
  if (myval_buffer == NULL){
   /* so here is a question, what to do if we cannot allocate memory?
	  We will end execution of program and attempt to report error  */
     k_error(sysmsg(10005));   /* Insufficient memory for buffer allocation */
	 /* We never come back from k_error */
  }

  /* move the passed argument string to our buffer */
  if (myval_len == 0){
	  myval_buffer[0] = '\0';
  } else {
   /* rem string length returned by k_get_c_string excludes terminator in count!*/ 
      myval_len = k_get_c_string(descr, myval_buffer, myval_len);
  }
  
  k_dismiss();   /* done with passed arg  descriptor */
                 /* Things to note                   */  
                 /* we use dismiss() instead of pop() because this is a string */ 
                 /* which may be made up of a linked list of string blocks     */
                 /* Using pop would not free the sting blocks                  */
                 /* After dismiss() e_stack  points to descr which will receive RTNVAL */

/* now extract arguments from the past arg string */

  if (myval_len == 0) {
	  argCnt = 1;                       /* always one args */
	  SDMEArgArray[0] = NullString();   /* simply a null string */

  }else{ 

    if (IsArgMV != 0){             /* MV Arg set */
  /*  Get number of fields in ARG */
      argCnt = Dcount(myval_buffer, myFM);
	/* if we found more args than we can process, only extract what we can hold */
	    if (argCnt > SD_MAX_ARGS) {
		    argCnt = SD_MAX_ARGS;
      }
	
	    for (argIdx = 0; argIdx < argCnt; argIdx++) { 
        /* rem Extract allocates our buffer space */
	      SDMEArgArray[argIdx]	= Extract(myval_buffer, argIdx+1, 0, 0);
	    }
    } else {  /* MV Flag not set, */
        argCnt = 1;                       /* always one args */
        SDMEArgArray[0] = myval_buffer;   /* we just point to the value buffer created earlier */  
    }
  }	  
  
  switch (key) {
	  
	  case  SDEXT_TestIt: 
	/* simple test to see if any of this works, output args to stdout  */
	    for (argIdx = 0; argIdx < argCnt; argIdx++) {
	      printf("Arg %d of %d\r\n",argIdx+1, argCnt);
 	      printf("'%s'\r\n",SDMEArgArray[argIdx]);
	    }
      snprintf( myErrMsg, SD_ERR_MSG_LEN, "op_sdext() found %d args\n", argCnt);
      k_put_c_string(myErrMsg, e_stack);   /* sets as descr as type string and place the value in myErrMsg into it */
                                           /* this will then get transferred to RTNVAL via */
      e_stack++;	
      break; 

    case SD_SALT:
      char* mysalt = NULL;
      mysalt = sd_salt();   /* Create unique salt and return base64 encoded  (caller mustr free!!!)   */                 
      if (mysalt != NULL){
        k_put_c_string(mysalt, e_stack);   /* sets as descr as type string and place the value in it */
                                           /* this will then get transferred to RTNVAL */
        e_stack++;
        free(mysalt);
      }	else {
        sdme_err_rsp(SD_Mem_Err);          /* only possible error in sd_salt ? */
      }
      break; 


    case SD_KEYFROMPW:  
      char* mykey = NULL;
      if (argCnt != 2){
        sdme_err_rsp(SD_EXT_ARG_CNT);     /* we need 2 args for this to work */
        break;
      }
      
      mykey =  sd_KeyFromPW(SDMEArgArray[0], SDMEArgArray[1]);  /* create key from password in [0] and salt in [1] */
                                                                /* sd_KeyFromPW(char* mypassword, char* mysalt)    */
      if (mykey != NULL){
        k_put_c_string(mykey, e_stack);   /* sets as descr as type string and place the value in it */
                                           /* this will then get transferred to RTNVAL */
        e_stack++;
        sodium_free(mykey);                /* key buffer was allocated via sodium_malloc, free via sodium_free*/
      }	else {
        sdme_err_rsp(process.status);      /* eror set in process.status */
      }
      break;

/* 19 Aug 26 Windows port - SCRAM-SHA-256 primitives for the API login
       exchange.  Every BINARY value is base64 - see gplsrc/sd_scram.c for why that
       is forced rather than chosen - while the password given to SD_PBKDF2 and
       the message signed by SD_HMACSHA256 are text, because neither is binary
       in the protocol either.  Each case is a thin adapter: check the argument count, parse any integers, make one
       call, and hand the result to the shared reply path. */

    case SD_SHA256: {
      if (argCnt != 1) {
        sdme_err_rsp(SD_EXT_ARG_CNT);
        break;
      }
      scram_reply(sd_scram_sha256(SDMEArgArray[0]));
      break;
    }

    case SD_HMACSHA256: {
      if (argCnt != 2) {
        sdme_err_rsp(SD_EXT_ARG_CNT);
        break;
      }
      scram_reply(sd_scram_hmac(SDMEArgArray[0], SDMEArgArray[1]));
      break;
    }

    case SD_PBKDF2: {
      long iterations;
      long dk_len;

      if (argCnt != 4) {
        sdme_err_rsp(SD_EXT_ARG_CNT);
        break;
      }
      iterations = scram_arg_long(SDMEArgArray[2]);
      dk_len = scram_arg_long(SDMEArgArray[3]);
      if (iterations < 0 || dk_len < 0) {
        sdme_err_rsp(SD_SCRAM_ERR);
        break;
      }
      scram_reply(sd_scram_pbkdf2(SDMEArgArray[0], SDMEArgArray[1],
                                  iterations, dk_len));
      break;
    }

    case SD_RANDBYTES: {
      long n_bytes;

      if (argCnt != 1) {
        sdme_err_rsp(SD_EXT_ARG_CNT);
        break;
      }
      n_bytes = scram_arg_long(SDMEArgArray[0]);
      if (n_bytes < 0) {
        sdme_err_rsp(SD_SCRAM_ERR);
        break;
      }
      scram_reply(sd_scram_random(n_bytes));
      break;
    }

    case SD_XORBYTES: {
      if (argCnt != 2) {
        sdme_err_rsp(SD_EXT_ARG_CNT);
        break;
      }
      scram_reply(sd_scram_xor(SDMEArgArray[0], SDMEArgArray[1]));
      break;
    }

    /* Answers "1" or "0".  A malformed argument is reported as an error rather
       than as "0", because by the time the login path compares these values
       both sides are the server's own - a decode failure there is a bug here,
       not a wrong password.  A caller deciding whether to admit a login must
       still treat the error as a refusal. */
    case SD_CTEQUAL: {
      int same;
      char answer[2];

      if (argCnt != 2) {
        sdme_err_rsp(SD_EXT_ARG_CNT);
        break;
      }
      same = sd_scram_ct_equal(SDMEArgArray[0], SDMEArgArray[1]);
      if (same < 0) {
        sdme_err_rsp(SD_SCRAM_ERR);
        break;
      }
      answer[0] = (char)('0' + same);
      answer[1] = '\0';
      k_put_c_string(answer, e_stack);
      e_stack++;
      break;
    }

    /* 15 Sep 26 Windows port - S.19/RELEASE_1.1 41.  The c= value this
       session's SCRAM login must carry.  "" when the session is not TLS,
       which APISRVR reads as "nothing to bind to: the login must say n,," -
       not an error, since a local pipe session legitimately has none.  Every
       socket session is TLS (sd_tlssrv.c), so a network client cannot reach
       the "" answer. */
    case SD_TLS_CBIND: {
      const unsigned char* binding = sd_tls_server_binding();
      char* attr;
      char empty[1] = {'\0'};

      if (binding == NULL) {
        k_put_c_string(empty, e_stack);
        e_stack++;
        break;
      }
      attr = sd_tls_cbind_attr(binding);
      if (attr == NULL) {
        sdme_err_rsp(SD_SCRAM_ERR);
        break;
      }
      k_put_c_string(attr, e_stack);
      e_stack++;
      free(attr);
      break;
    }

    /* 13 Aug 26 Windows port - the SD_Py* keys were handled here.  Embedded
       Python is gone (PROJECT_STATUS.md 5.15), so they now fall through to
       the unknown-key response below, which is what they are. */

    /* 5 Sep 26 Windows port - SD_EUID_SET and SD_EUID_RESTORE were handled
       here, through sdext_eguid.c.  That was the Linux setuid model
       (getpwnam/setegid/seteuid), its only callers were two CPROC blocks that
       could never compile in, and it is gone: PRE_RELEASE_FIXES 168,
       PROJECT_STATUS.md 5.5.  These keys now fall through to the unknown-key
       response below, which is what they are. */

    /* 12 Sep 26 Windows port - THE PYTHON LIFECYCLE AND RUN KEYS ARE BACK,
       over a helper process rather than an embedded interpreter.
       PROJECT_STATUS.md 5.27.  The object keys are the OTHER opcode,
       op_sdpyobj.c (0xCFFE); these six are the ones the PY_* wrappers send
       through SDEXT, and the split is the one the BASIC surface already had.

       ***THE GATE IS NOT HERE, AND THAT IS DELIBERATE.***  Section 8
       constraint 4: a permission test inside this switch would run with
       process.program already pointing at an $internal PY_* wrapper, and
       os_permitted() returns TRUE on HDR_INTERNAL before it ever reads the
       username - so it would pass for every user, always.  The test lives in
       sdpy_session.c, at the moment the helper process is STARTED, which is
       the only point where the real caller is still visible. */
    case SD_PyInit:
      py_ext_int("INIT", NULL);
      break;

    case SD_PyFinal:
      py_ext_int("FIN", NULL);
      break;

    case SD_IsPyInit:
      /* ***THIS ONE MUST NOT START A HELPER TO ANSWER.***  "Is Python
         running?" asked of a session that has none is answered 0, not by
         starting one to find out - and not by a gate refusal either, because
         the honest answer to the question is still no. */
      py_ext_isinit();
      break;

    case SD_PyRunStr:
      py_ext_int("RUNSTR", SDMEArgArray[0]);
      break;

    case SD_PyRunFile:
      py_ext_int("RUNFILE", SDMEArgArray[0]);
      break;

    case SD_PyGetAtt:
      py_ext_str("GETATTR", SDMEArgArray[0]);
      break;

    default:
      /* unknown key */
      sdme_err_rsp(SD_EXT_KEY_ERR);

  }
  
  /* release our arg Buffers  */
  for (argIdx = 0; argIdx < SD_MAX_ARGS; argIdx++) {
	  if (SDMEArgArray[argIdx] != NULL ){
	    free(SDMEArgArray[argIdx]);
	    SDMEArgArray[argIdx] = NULL;
	  }
  }  
  /* and the val buffer */	
  if (myval_buffer != NULL){
    if (IsArgMV != 0) {      /* rem if IsArgMV not set, we pointed DMEArgArray[0] to myval_buffer*/
	    free(myval_buffer);    /* do not want to attempt to free the memory again!!*/
    } 
  } 

  return;
}

char* NullString() {
  char* p;

  /* 15 Aug 26 Windows port - RETURN NULL, NOT A STATIC BUFFER.  See the same
     fix in ctype.c's CNullString().  The result goes into SDMEArgArray[0] at
     line 170 and the release loop below frees every non-NULL entry, so
     returning static storage on an out-of-memory made SD free() something it
     never allocated.  The loop already skips NULL.                        */
  p = malloc(1);
  if (p == NULL)
    return NULL;
  *p = '\0';
  return p;
}

/* 19 Aug 26 Windows port - shared reply path for the sd_scram primitives.
   Every one of them answers a malloc'd base64 string or NULL, so success and
   failure look the same at every call site.  Note sdme_err_rsp() pushes its
   own empty result, so only the success path touches e_stack here. */
Private void scram_reply(char* value) {
  if (value == NULL) {
    sdme_err_rsp(SD_SCRAM_ERR);
    return;
  }
  k_put_c_string(value, e_stack);
  e_stack++;
  free(value);                /* malloc'd in sd_scram.c, not sodium_malloc'd */
}

/* Answers -1 for anything that is not a clean non-negative decimal integer.
   The bounds themselves are checked inside sd_scram.c, which is where they are
   documented; this only has to reject text that is not a number at all. */
Private long scram_arg_long(const char* text) {
  char* end;
  long value;

  if (text == NULL || *text == '\0')
    return -1;

  errno = 0;
  value = strtol(text, &end, 10);
  if (errno != 0 || *end != '\0' || value < 0)
    return -1;

  return value;
}

/* ======================================================================
   12 Sep 26 Windows port - the three Python adapters.  PROJECT_STATUS.md 5.27.

   Each is a thin wrapper round one request to sdpy.exe.  Nothing of Python
   appears in this file: section 5.3 keeps the runtimes apart and the only
   thing crossing is bytes on a pipe.
   ====================================================================== */

/* One exchange.  Returns the helper's status, or SD_PyErr_NoHelper when there
   was no exchange at all - a refused gate, a helper that will not start, or a
   pipe that broke.  Those are not Python errors and must not borrow a Python
   error's number. */
Private int py_ext_call(const char* verb, const char* arg,
                        char** payload, size_t* plen) {
  SDPY* s;
  int err_code = 0;
  int status = 0;

  if (payload != NULL) *payload = NULL;
  if (plen != NULL) *plen = 0;

  s = sdpy_session(&err_code);
  if (s == NULL)
    return err_code != 0 ? err_code : SD_PyErr_NoHelper;

  if (sdpy_call(s, verb, arg, arg ? strlen(arg) : 0, NULL, 0, NULL, 0,
                &status, payload, plen) != 0)
    return SD_PyErr_NoHelper;

  return status;
}

/* Integer result: the status is the value, which is what PY_INITIALIZE,
   PY_FINALIZE, PY_RUNSTRING and PY_RUNFILE all return. */
Private void py_ext_int(const char* verb, const char* arg) {
  char* payload = NULL;
  size_t plen = 0;
  int status = py_ext_call(verb, arg, &payload, &plen);

  process.status = status;
  InitDescr(e_stack, INTEGER);
  (e_stack++)->data.value = (int32_t)status;
}

/* String result: PY_GETATTR's "on success returned string or empty string on
   failure".  The traceback in the payload on an error path is for a human and
   is NOT handed back as the value - that would make a failed call look like a
   successful one that returned prose. */
Private void py_ext_str(const char* verb, const char* arg) {
  char* payload = NULL;
  size_t plen = 0;
  int status = py_ext_call(verb, arg, &payload, &plen);

  process.status = status;
  if (status != 0 || payload == NULL)
    k_put_c_string("", e_stack);
  else
    k_put_string(payload, (int)plen, e_stack);
  e_stack++;
}

/* PY_IS_INITIALIZED, which must answer without starting anything. */
Private void py_ext_isinit(void) {
  int running = 0;

  if (sdpy_session_running()) {
    char* payload = NULL;
    size_t plen = 0;
    if (py_ext_call("ISINIT", NULL, &payload, &plen) == 0 &&
        payload != NULL && plen >= 1 && payload[0] == '1')
      running = 1;
  }

  process.status = 0;
  InitDescr(e_stack, INTEGER);
  (e_stack++)->data.value = (int32_t)running;
}

/* generic error return with null response, setting process.status */
Private void sdme_err_rsp(int errNbr){
  char EmptyResp[1] = {'\0'}; /*  empty return message  */
  k_put_c_string(EmptyResp, e_stack); /* sets descr as type string, empty */
  e_stack++;
  process.status = errNbr;

}
